on:
  workflow_dispatch:

name: Scrape-Fillers
jobs:
  Scrape-Fillers:
    name: Scrape-Fillers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Cache Request Cache Database
        uses: actions/cache@v4
        with:
          path: ./request_cache.sqlite
          key: ${{ runner.os }}-sqlite-cache-${{ hashFiles('bun.lockb') }}-v1
          restore-keys: |
            ${{ runner.os }}-sqlite-cache-

      - name: Install Dependencies and Run Scraper
        run: |
          bun install
          bun run ./Filler-Scraper/index.ts

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: my-artifact
          path: ./Filler-Scraper/fillers.json

      - name: Set today's date to env
        run: echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV

      - name: Extract Anime Keys from JSON
        id: extract_keys
        run: |
          # Use jq to get all keys, pipe them into a multiline list format
          # (prepended with * ), and save the result to an environment variable.
          ANIME_KEYS=$(jq -r 'keys[] | "* " + .' ./Filler-Scraper/fillers.json)

          # Set the list of keys to an output variable for use in the next step
          echo "ANIME_KEYS<<EOF" >> $GITHUB_ENV
          echo "$ANIME_KEYS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set dynamic release variables
        id: set_vars
        run: |
          DATE=$(date +'%d.%m.%Y')
          echo "RELEASE_TAG=daily-AniWorld-filler-release" >> $GITHUB_ENV
          echo "ASSET_NAME=AniWorld_Fillers_$DATE.json" >> $GITHUB_ENV

      - name: Release and Upload Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Daily AniWorld Fillers"
          tag_name: ${{ env.RELEASE_TAG }}
          files: ./Filler-Scraper/fillers.json
          body: |
            This release contains the latest scraped filler data, generated on ${{ env.DATE }}.

            ---

            ## Scraped Anime Series:
            ${{ env.ANIME_KEYS }}
